name = "secretmessenger-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

# KV नेमस्पेस बाइंड करें
[[kv_namespaces]]
binding = "KV"
id = "93db2f4666424251b96ea44459d73b5e"   # Cloudflare डैशबोर्ड से लें

# Durable Objects बाइंडिंग
[[durable_objects]]
bindings = [{ name = "CHAT_ROOM", class_name = "ChatRoom" }]

# (वैकल्पिक) डिप्लॉयमेंट के लिए
[env.production]
workers_dev = true